apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-java
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/dbuddenbaum/helloworld-java
          env:
            - name: TARGET
              value: "SparkJava Sample v1"
      nodeSelector:
        beta.kubernetes.io/arch: amd64