---
- name: fix search in /etc/resolv.conf
  lineinfile:
    backrefs: yes
    line: 'search\g<1>'
    path: /etc/resolv.conf
    regexp: '^(?:domain|search)(\s.*)'
- name: make /etc/resolv.conf immutable
  changed_when: false
  file:
    attributes: +i
    path: /etc/resolv.conf
- name: disable swap-space
  shell: dphys-swapfile uninstall && update-rc.d dphys-swapfile disable
  args:
    removes: /var/swap
- name: rpi-update
  changed_when: "'already up to date' not in rpi_update.stdout or 'reboot is needed' in rpi_update.stdout"
  environment:
    SKIP_WARNING: 1
  notify: reboot system
  register: rpi_update
  shell: rpi-update
- meta: flush_handlers
