---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: rosettaathomedata
  namespace: community-grid
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rosettaathome
  namespace: community-grid
  labels:
    app: rosettaathome
spec:
  replicas: 1
  template:
    metadata:
      name: rosettaathome
      namespace: community-grid
      labels:
        app: rosettaathome
    spec:
      containers:
        - name: rosettaathome
          image: boinc/client:arm64v8
          imagePullPolicy: Always
          env:
            - name: TZ
              value: "America/New_York"
            - name: BOINC_GUI_RPC_PASSWORD
              value: "123"
            - name: BOINC_CMD_LINE_OPTIONS
              value: "--allow_remote_gui_rpc"
          resources:
            limits:
              cpu: '1'
            requests:
              cpu: 500m
          volumeMounts:
            - mountPath: /var/lib/boinc
              name: rosettaathomedata
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 31416
              name: manager
              protocol: TCP
      nodeSelector:
              kubernetes.io/arch: arm64
      volumes:
        - name: rosettaathomedata
          persistentVolumeClaim:
            claimName: rosettaathomedata
  selector:
    matchLabels:
      app: rosettaathome
---
apiVersion: v1
kind: Service
metadata:
  name: rosettaathome
  namespace: community-grid
  annotations:
    metallb.universe.tf/address-pool: default
spec:
  selector:
    app: rosettaathome
  ports:
    - port: 80
      name: http
      protocol: TCP
    - port: 443
      name: https
      protocol: TCP
    - port: 31416
      name: manager
      protocol: TCP
  type: LoadBalancer