---
apiVersion: v1
kind: Service
metadata:
  name: bear
  namespace: default
spec:
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: animals
    task: bear
---
apiVersion: v1
kind: Service
metadata:
  name: moose
  namespace: amd64default
spec:
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: animals
    task: moose
---
apiVersion: v1
kind: Service
metadata:
  name: hare
  namespace: default
spec:
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: animals
    task: hare